In [8]:
import numpy as np
q=np.arange(13)
q

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
a=q.reshape(13,1)
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

ar2=np.arange(25).reshape(5,5)
ar2

In [16]:
ar2=np.arange(25).reshape(5,5)
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [15]:
ar2[2:3,2:5]

array([[12, 13, 14]])

In [17]:
ar2[3:5,0:2]

array([[15, 16],
       [20, 21]])

In [22]:
ar2[-3:-1,-4:-2]

array([[11, 12],
       [16, 17]])

In [25]:
ar3=np.arange(50).reshape(5,10)
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
np.sum(ar3,axis=0)

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [27]:
np.sum(ar3,axis=1)

array([ 45, 145, 245, 345, 445])

In [28]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.sum(ar3)

1225

In [ ]:
# mean->average
# median->center value
# mode->max num of repeated element
# vaiance->median/total num of elements
# std->square root of variance

In [35]:
np.linspace(1,10,4)
            

array([ 1.,  4.,  7., 10.])

In [36]:
np.linspace(1,10,4,dtype=int)

array([ 1,  4,  7, 10])

In [37]:
np.linspace(1,10,4,dtype=complex)

array([ 1.+0.j,  4.+0.j,  7.+0.j, 10.+0.j])

In [39]:
len(ar3)

5

In [40]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [41]:
np.linspace(1,50,5,retstep=True)

(array([ 1.  , 13.25, 25.5 , 37.75, 50.  ]), 12.25)

In [108]:
np.random.randint(1,70)

67

In [175]:
np.random.randint(1,70,2)

array([40, 24])

In [ ]:
# rand()->To get the randomly generated valued from 0 to 1,based on uniform distribution


In [179]:
# Uniform Distrubution
np.random.rand(9)

array([0.78780442, 0.64049601, 0.19662976, 0.50686853, 0.66248604,
       0.2712724 , 0.5026863 , 0.36267651, 0.64669014])

In [180]:
# Normalised Distrubution
np.random.randn(10)

array([ 0.93548511,  0.20991942,  0.40843878, -0.79520567, -1.26122485,
        0.28580739,  1.64475139,  0.74854293, -0.07661313,  1.39647402])

In [181]:
np.random.randn(5,4)

array([[-1.60622521,  1.1471669 , -1.31202763, -1.73219941],
       [ 0.29924571, -0.41963203, -1.27635972, -2.02826527],
       [ 0.42214364, -0.50489638,  0.77423877, -1.07552134],
       [-0.23937532,  0.51479095,  0.52264661, -1.23890999],
       [-1.5204106 ,  0.3165973 , -0.66150304,  2.83718732]])

In [182]:
ar3.min()

0

In [183]:
ar3.max()

49

In [ ]:
#every row turn into list

In [184]:
ar3.tolist()

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
 [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
 [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]

In [ ]:
#to print the min value of index

In [187]:
print(ar3.argmin())

0


In [ ]:
#to print the max value of index

In [188]:
print(ar3.argmax())

49


In [190]:
np.sin(ar3)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
         0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
        -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
        -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
         0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265]])

In [191]:
np.cos(ar3)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
        -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
         0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753],
       [ 0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
        -0.90369221, -0.12796369,  0.76541405,  0.95507364,  0.26664293],
       [-0.66693806, -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,
         0.52532199, -0.43217794, -0.99233547, -0.64014434,  0.30059254]])

In [195]:
np.tan(ar3)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01,  1.15782128e+00, -3.38051501e+00,
        -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
         3.00632242e-01,  3.49391565e+00, -1.13731371e+00,
         1.51589471e-01],
       [ 2.23716094e+00, -1.52749853e+00,  8.85165604e-03,
         1.58815308e+00, -2.13489670e+00, -1.33526407e-01,
         1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
         8.87142844e-01],
       [-6.40533120e+00, -4.41695568e-01,  6.61006041e-01,
        -7.53130148e+01, -6.23498963e-01,  4.73814720e-01,
         7.75047091e+00, -8.40771255e-01,  3.10309661e-01,
         3.61455441e+00],
       [-1.11721493e+00,  1.60656699e-01,  2.29138799e+00,
        -1.49838734e+00,  1.77046993e-02,  1.61977519e+00,
        -2.08661353e+00, -1.24527568e-01,  1.20012724e+00,
        -3.

In [197]:
np.cos(ar3)/np.sin(ar3)

C:\Users\Hp\AppData\Local\Temp\ipykernel_18600\1609718453.py:1: RuntimeWarning: divide by zero encountered in divide
  np.cos(ar3)/np.sin(ar3)


array([[            inf,  6.42092616e-01, -4.57657554e-01,
        -7.01525255e+00,  8.63691154e-01, -2.95812916e-01,
        -3.43635300e+00,  1.14751542e+00, -1.47065064e-01,
        -2.21084541e+00],
       [ 1.54235105e+00, -4.42574133e-03, -1.57267341e+00,
         2.15972864e+00,  1.38033720e-01, -1.16823331e+00,
         3.32632320e+00,  2.86211833e-01, -8.79264876e-01,
         6.59676425e+00],
       [ 4.46995109e-01, -6.54665115e-01,  1.12973210e+02,
         6.29662222e-01, -4.68406739e-01, -7.48915531e+00,
         8.48353752e-01, -3.05464410e-01, -3.55328645e+00,
         1.12721419e+00],
       [-1.56119952e-01, -2.26400279e+00,  1.51284548e+00,
        -1.32779175e-02, -1.60385191e+00,  2.11052962e+00,
         1.29024418e-01, -1.18938414e+00,  3.22258739e+00,
         2.76659275e-01],
       [-8.95082918e-01,  6.22445256e+00,  4.36416706e-01,
        -6.67384176e-01,  5.64821794e+01,  6.17369624e-01,
        -4.79245430e-01, -8.03035035e+00,  8.33244979e-01,
        -3.

In [198]:
1/np.sin(ar3)

C:\Users\Hp\AppData\Local\Temp\ipykernel_18600\4009155036.py:1: RuntimeWarning: divide by zero encountered in divide
  1/np.sin(ar3)


array([[          inf,    1.18839511,    1.09975017,    7.0861674 ,
          -1.32134871,   -1.04283521,   -3.57889955,    1.52210106,
           1.01075622,    2.42648664],
       [  -1.83816396,   -1.00000979,   -1.8636796 ,    2.38000584,
           1.0094817 ,    1.53778056,   -3.47338826,   -1.0401525 ,
          -1.33158054,    6.67212849],
       [   1.09535594,    1.19523488, -112.9776361 ,   -1.18172523,
          -1.10426667,   -7.55562355,    1.31137488,    1.04561394,
           3.69132017,   -1.50685494],
       [  -1.01211335,   -2.4750169 ,    1.81347772,    1.00008815,
           1.89006374,   -2.33545183,   -1.00828929,   -1.55390947,
           3.37417686,    1.03756463],
       [   1.34207803,   -6.30426917,   -1.09108182,   -1.20224858,
          56.49103101,    1.17522136,    1.10890765,    8.0923746 ,
          -1.30165172,   -1.04848988]])

In [199]:
1/np.cos(ar3)

array([[  1.        ,   1.85081572,  -2.40299796,  -1.01010867,
         -1.52988566,   3.52532009,   1.04148193,   1.3264319 ,
         -6.87285064,  -1.09753791],
       [ -1.19179351, 225.95305931,   1.18503918,   1.101993  ,
          7.31329782,  -1.31633001,  -1.0442125 ,  -3.63420508,
          1.5144248 ,   1.01142443],
       [  2.45048752,  -1.82571952,  -1.00003918,  -1.87676056,
          2.35749526,   1.00887527,   1.54578781,  -3.42303032,
         -1.03884678,  -1.33679558],
       [  6.48292123,   1.093204  ,   1.19871973, -75.31965347,
         -1.17845278,  -1.10657146,  -7.81471684,   1.30648242,
          1.04703968,   3.75033379],
       [ -1.49938961,  -1.01282307,  -2.50009178,   1.80143404,
          1.00015672,   1.90359441,  -2.31386171,  -1.00772373,
         -1.56214769,   3.32676249]])

In [228]:
np2=np.array([1,2,3,9,7])
np3=np.array([4,5,6,2,5,88])
if(len(np2)>len(np3)):
    l=abs(len(np2)-len(np3))
    a=np.append(np3,np.ones(l))
    np4=sum(np2*a)
else:
    l=abs(len(np2)-len(np3))
    a=np.append(np2,np.ones(l))
    np4=sum(np3*a)
np4


173.0

In [225]:
w=-6
e=abs(w)
e

6

In [230]:
np1=np.array([1,34,56,78,np.nan,])
np1[np.isnan(np1)]

array([nan])

In [233]:
a=9
~a


-10

In [237]:
np1[~np.isnan(np1)]

array([ 1., 34., 56., 78.])

In [236]:
np2=np.array([1,2,3,9,7])
np3=np.array([4,5,6,2,5])
np.dot(np2,np3)

85

In [1]:
import pandas as pd

In [ ]:
# python is defines as an open source libraray that provides high performance data manipulation in python.data anlaysis 
#requires lot of processing such as restructuring,cleaning,mergin,manipulating etc... we prefer pandas to perform the 
#above functionalities coz it is fast,simple than other tools.
#pandas is built on numpy, numpy is required for operating pandas


In [ ]:
#pandas series is a data structure with one dimensional labelled array
#it is a primary building block of dataframe,making its rows and columns

In [34]:

import numpy as np
import pandas as pd
labels=['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':100,'b':200,'c':300}


In [35]:
import pandas as pd
pd.Series(d)

a    100
b    200
c    300
dtype: int64

In [36]:
pd.series(data=[print(),len,sum])

AttributeError: module 'pandas' has no attribute 'series'

In [37]:
ser1=pd.Series([1,2,3,4,5],['USA','INDIA','JAPAN','GERMANY','PORTUGAL'])
ser1

USA         1
INDIA       2
JAPAN       3
GERMANY     4
PORTUGAL    5
dtype: int64

In [38]:
#access values using indexing

In [39]:
ser1[0:3]

USA      1
INDIA    2
JAPAN    3
dtype: int64

In [40]:
ser2 = pd.Series([5,6,7,8],['USA','BRAZIL','CANADA','UK'])
ser1+ser2

BRAZIL      NaN
CANADA      NaN
GERMANY     NaN
INDIA       NaN
JAPAN       NaN
PORTUGAL    NaN
UK          NaN
USA         6.0
dtype: float64

In [41]:
ser2.drop('USA')

BRAZIL    6
CANADA    7
UK        8
dtype: int64

In [42]:
#dataframe
#pd.DataFrame(datas,row_label,col_label)

In [43]:
df = pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0 -1.258258  0.989928 -0.772448 -0.016822
1 -0.458532  0.396795  1.297114 -0.491574
2 -0.140191  1.614215 -0.642534 -0.485091
3 -1.057364  1.068651 -1.788962 -0.302022
4  2.455606 -0.996899  0.290486  1.787901

In [44]:
df = pd.DataFrame(np.random.randn(5,4),["a","b","c","d","e"],["a","b","c","d","e"])


ValueError: Shape of passed values is (5, 4), indices imply (5, 5)

In [45]:
df

0         1         2         3
0 -1.258258  0.989928 -0.772448 -0.016822
1 -0.458532  0.396795  1.297114 -0.491574
2 -0.140191  1.614215 -0.642534 -0.485091
3 -1.057364  1.068651 -1.788962 -0.302022
4  2.455606 -0.996899  0.290486  1.787901

In [46]:
#to convert dictionary to dataframes

In [47]:
d={"col1":[1,2],"col2":[3,4],"col3":[5,6]}
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [48]:
df=pd.DataFrame(data=d)
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [49]:
df=pd.DataFrame(d,["row1","row2"])
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [50]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [51]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [52]:
type(df)

pandas.core.frame.DataFrame

In [53]:
df.dtypes

col1    int64
col2    int64
col3    int64
dtype: object

In [55]:
#to get information about database
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, row1 to row2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      int64
 2   col3    2 non-null      int64
dtypes: int64(3)
memory usage: 64.0+ bytes


In [56]:
df.values

array([[1, 3, 5],
       [2, 4, 6]], dtype=int64)

In [57]:
df.axes

[Index(['row1', 'row2'], dtype='object'),
 Index(['col1', 'col2', 'col3'], dtype='object')]

In [58]:
df.ndim

2

In [59]:
df.size

6

In [63]:
#to access multiple rows
#to access multiple  columns

KeyError: "None of [Index(['0', '1', '2'], dtype='object')] are in the [columns]"

In [64]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [65]:
df['new']=df['col1']

In [66]:
df

col1  col2  col3  new
row1     1     3     5    1
row2     2     4     6    2

In [67]:
df.drop('new',axis=1)

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [84]:
df.drop('col3',axis=1,inplace=True)

In [85]:
df

col1  col2
row1     1     3
row2     2     4

In [86]:
df

col1  col2
row1     1     3
row2     2     4